""" TWILIO CONFIGURATION """

SSID = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
AUTH_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
FROM_NUMBER='+12674151466'
TO_NUMBER = '+9194XXXXXXX'

""" BOLT IOT CONFIGURATION """

API_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
DEVICE_ID = 'BOLTXXXXXX'
FRAME_SIZE = 10
MUL_FACTOR = 6


""" TWITTER CONFIGURATION"""

consumer_key = 'XXXXXXXXXXXXXXXXX'
consumer_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
access_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
access_token_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
